### ISSUE TITLE
Run evaluate.py problem

### ISSUE THREAD

**Issue by pengxiang-pang** [robin-shaun/Multi-UAV-Task-Assignment-Benchmark#1]
aco_task_assignmet = aco_result.get()[0]
  File "D:\Anaconda3\lib\multiprocessing\pool.py", line 657, in get
    raise self._value
ValueError: list.remove(x): x not in list
Hello, the above problems may occur in the process of operation. After repeated run, it is found that this problem sometimes occurs early and sometimes late. May I ask why?

**Comment by robin-shaun** [comment]
You can debug to find the reason.

**Comment by pengxiang-pang** [comment]
Thank you very much, I'll look into it more carefully.

**Comment by BTMOP** [comment]
I would like to ask you how to solve this problem? thank you very much.
lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
ValueError: list.remove(x): x not in list
