### ISSUE TITLE
Return to depot constraint

### ISSUE THREAD

**Issue by danifuertes** [robin-shaun/Multi-UAV-Task-Assignment-Benchmark#5]
Could it be possible to adapt all the algorithms to consider the constraint of returning to the depot? How should it be made?

**Comment by robin-shaun** [comment]
For example,  change https://github.com/robin-shaun/Multi-UAV-Task-Assignment-Benchmark/blob/master/ga.py#L64
to `if t + t_flyback < self.time_lim: `

**Comment by danifuertes** [comment]
Thanks! It works correctly! If someone is interested, what I did (please tell me if something is wrong) is:

GA:
-Change [line 64](https://github.com/robin-shaun/Multi-UAV-Task-Assignment-Benchmark/blob/master/ga.py#L64) to `if t + self.map[seq[post], 0] / self.vehicles_speed[i] < self.time_lim:`
-Change [line 167](https://github.com/robin-shaun/Multi-UAV-Task-Assignment-Benchmark/blob/64e38b4b97b36ec027016e5fb7892ad6c9ac181d/ga.py#L167) to `if t + self.map[seq[post], 0] / self.vehicles_speed[i] < self.time_lim:`

PSO:
-Change [line 165](https://github.com/robin-shaun/Multi-UAV-Task-Assignment-Benchmark/blob/64e38b4b97b36ec027016e5fb7892ad6c9ac181d/pso.py#L165) to `if t + self.Distance[m1][0] / self.vehicles_speed[i] <= self.time_all:`
-Change [line 338](https://github.com/robin-shaun/Multi-UAV-Task-Assignment-Benchmark/blob/64e38b4b97b36ec027016e5fb7892ad6c9ac181d/pso.py#L338) to `if t + self.Distance[m1][0] / self.vehicles_speed[i] <= self.time_all:`

ACO:
-Change [line 77](https://github.com/robin-shaun/Multi-UAV-Task-Assignment-Benchmark/blob/64e38b4b97b36ec027016e5fb7892ad6c9ac181d/aco.py#L77) to `if time_sum[ant] + dis_mat[path_mat[ant][0]][visit_next] / self.ant_vel[ant_type] > self.cut_time:`
